export const NOT_ALLOWED = '/not-allowed';
export const LOGIN = '/login';
export const SIGN_UP = '/sign-up';
export const ROOT = '/';
export const RESTAURANTS = '/restaurants';
export const OWNED_RESTAURANTS = '/owned-restaurants';
export const RESTAURANT_DETAIL = '/restaurant/:restaurantId';
export const getRestaurantDetail = (id: number) => `/restaurant/${id}`;
export const USER_PROFILE = '/user-profile';
export const USER_MANAGEMENT = '/user-management';
